id: A39C4F5D4
title: The Twenty-Eight Commitments
type: translation
pechas:
- I410040C4
- I48249F1D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:56.140586
  last_modified_at: 2023-01-04 12:37:56.140592
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I410040C4/86C4: '8259'
  I48249F1D/57A6: '8259'
